"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Jogo_1 = require("./Jogo");
const Personagem_1 = require("./Personagem");
const Espada_1 = require("./Espada");
const Arco_1 = require("./Arco");
const Varinha_1 = require("./Varinha");
const Veneno_1 = require("./Veneno");
const Regenerar_1 = require("./Regenerar");
const jogo = new Jogo_1.Jogo();
const guerreiro = new Personagem_1.Personagem('Felipe', 100);
const goblin = new Personagem_1.Personagem('Goblin', 100);
const scarlet = new Espada_1.Espada(45, 2);
const eudora = new Arco_1.Arco(20, 1, 1);
const plink = new Varinha_1.VarinhaMagica(1, 5, 250);
guerreiro.equiparNovaArma(scarlet);
const curandeira = new Personagem_1.Personagem('Flor', 30, plink);
const aliado = new Personagem_1.Personagem('Otavio', 100, eudora);
jogo.adicionarPersonagem(guerreiro);
jogo.adicionarPersonagem(curandeira);
jogo.adicionarPersonagem(aliado);
jogo.adicionarPersonagem(goblin);
jogo.escutadorDeTurno(guerreiro);
jogo.escutadorDeTurno(curandeira);
jogo.escutadorDeTurno(aliado);
jogo.escutadorDeTurno(goblin);
guerreiro.atacar(goblin);
guerreiro.atacar(goblin);
curandeira.atacar(goblin);
aliado.atacar(goblin);
jogo.passarTurno();
curandeira.atacar(goblin);
aliado.atacar(goblin);
eudora.recarregarFlechas();
plink.recarregarMana();
curandeira.adicionarItemInventario('Foto Antiga', 1);
curandeira.adicionarItemInventario('Pocao Vitalidade', 10);
const denteDeVibora = new Veneno_1.Veneno(10, 1, goblin);
const asaDeAnjo = new Regenerar_1.Regenerar(50, 2, guerreiro);
const guspeDegoblin = new Veneno_1.Veneno(20, 2, guerreiro);
jogo.escutadorDeTurno(guspeDegoblin);
jogo.escutadorDeTurno(denteDeVibora);
jogo.escutadorDeTurno(asaDeAnjo);
jogo.passarTurno();
guerreiro.curar(10);
jogo.passarTurno();
guerreiro.atacar(goblin);
//# sourceMappingURL=File.js.map